use_frameworks!

target 'ZCMobilePayment_Example' do
  pod 'ZCMobilePayment', :path => '../'

  target 'ZCMobilePayment_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
